apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-osean-test
  template:
    metadata:
      labels:
        app: blue-osean-test
    spec:
      containers:
        - name: blue-osean-test
          image: {{ .Values.images }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
